---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-updater-ghcr
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBOn6iPcL4DGLFk+LwfQowvcdLolF8LAzdurWFXLwfEmbHNDUT2QxoSvDN2Wiq8MadIAZAdCqo3MeePVtYMrrVW65Kj+eeJxCNC3d6TfpxFdnegR8t4MW+Kh8gpyJZzATjCaHdmzfrK7L0LDrMmr5zwL12VR4Cyv1sozBfKmXKSUB/zxGoQyyydRZkx/SzNmsblstuhql8ukap7U9VbTpYzaMg4mTPfvMD5JH82A1Kayyoao+E4ylNSWTHe6utQmjOD10zHynZB0QBT7+K8MORB6a1afeCJC5T2IEoYBypC+q/xYRvMFXkNOleuXyERjHT1izbmHfMunKKBifjBucWDAA/ApN3v8HkeaQjgeBuAfRCL9LQcED19BfNBc1reKh1LtiAszU1ZoYBLvQ5hKDREMnP+uCRNh6o6MYE4potc4YPNticgq6fGGTW8v8pqPgOV7TLyI7G3BZwYuxCDGxKScEYXSGfUBu8d3uhonzAdJ74rzvYKyjxFpq1gO/ruSxQ2rJYr5iCH3ZuYK4eC+5oei3s7eyXPmfgo2f+Q9t0ZLEsjTv8S3IvgSxVFCwfP22rTJHdf4ibfcdXZu2mwowSqIuFuphiLw1nYIn+H1BFFQoiUaa/0ILb2pLl07aJRxlfHXFUhPOCD9bWkq4ImMEJMA01rAeZpYBuYFrbsHau9PbuJD5NjuhJazHkuWVgXkzozChlPCZ10nsk1PlE6/2oDJESVjA9lG7cABb02VY2Uz0xvF7SzTVo7jvbuwe1K29uMngqr4ZpMS+qjOqa2/yt+2AHhajdlRCR5B+7tLBpNApat7d0K2iU6ZbArpi18ro++PHttkPumwtAYYRYHLJy4udMoxhEfU4MjZo3MzAL/JvuglIShnAkheWUe+H1UddhpGK/4EAyhF1T1Jib1F0qVcx3nR8Ndnmx5gA==
  template:
    metadata:
      creationTimestamp: null
      name: image-updater-ghcr
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
