---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-updater-ghcr
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgA1KTJ+0IU2ld15N/8U47+wEs8Q/XbWhx76ytc69tL3TeS8eFAHiXZd3ll+Va/Pnsv5BvVOAoDV4iJnd2OMFxZ60qSe7KofB91JATDu6Fh911ZL3Bq+6qdnDWBArxvyhw0YohynGjp45ik7yKkGOCxOJE49a53x+YHcCUAWtB8vSDc7ATK/PwWGsaDldXCDbW6eqpmbVPwO/7qXjWUN8t4rDwDAtydk3CuFDELnn1HQ+F16V1mt62Fcd6gsTaJhzhAviluk70WJMrus1TpIN8JzIreXXcH20Jr0JvzDgLolAldyGWpV6udXHIsdKrrDwL4n/10NkM5eWucjXaHle4Wg30hrA53QdwqMHeMjqan6wEcxVEgkQWnI4/Q7PKe47jjQd48DidmTr8ZfmP4wEb9E7SrLlubBRTYzeDl4ng7k2qD+EgEgcvd1oC5U8LabcY6TOZfXfoOCgojGH8Eolgfq/Z0+jPz6x4Jd0D2n3UDEbUbWAaN3H3yYYhoaOuD3i96fkNouDWL27FVF1dqt071QrZkMqm9EAb/RhYZP2Eu2AWaA62CeJZP6TYlwGQQPJchvSYBbrRCHTEUzdz3zXTPVQnFboybKZ6wQSGM5Db+OLe08vZyGhJ6FjgUF0cMT4JCL0qB4p0JanmtOsT6ddVveZ6sykZnmRiJp2eUyGwSHFeaSZNPwmrvrB8mHD5gWb7VyANCQMErQZ42pt7kvCFlzb8ORkpWrfFIn02sF0JaC27ys+7EE2i+/X4HEUPBRIulBMYdrOJs2O/K/v6gJgBU12XGUbCr8XVOi0LSCaLNhIz/vgv3UyrK5hDNAKeRkWcAEHsG4U81+NLySm+aVLYU1V/Nz+2n5BQpaOZ3f0UvUnDbR65BQOFIY4RSNwCn/ZHpKE02/ZL0qJhlFprpWZOaR3RKvG1fbua0r9w==
  template:
    metadata:
      creationTimestamp: null
      name: image-updater-ghcr
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
