---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-updater-ghcr
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgApMlGd8eRNMWMJhnZ/LMOIBUYtZgpCxMGtjKjBh/RiGuXYzz7psgBTGiAeZ0DE2m6/G4X5PHYiVa+eggBQjBhtiZn4f4yxFy91Oq/YX6A8E/y3dSvRx0CT1taNIFdEnuV+lQci3VihO68YjaXCtXiVD2jZ07fJQ+OSBUKCF9x45xPVn/m73wFSbQQfcJCR/un3ppSYguUSt5iLQVuswS+SF2kIZG9TjQhprz4NG3oF7rarlbOm4N47uDFkTvXX0dSGRzqEwRGc5n8JH9u4jX+2rGav7UUgnnhBTvZw//a01lI64qINHZZKNEMul534wPenV3TdQsMX6Pdl/Y/8Y8rmPcVnmH3jUbOXUDVQGAM7E4ENGhh0eQEwxpgdB8xcwJ3A+u6ayGd29sqZC7A/wTKX2+5LqGB6k7GAKUmOWcsZLCMnBvgA8peUTbzSC/E9BJykKpGJblob5K3U5NRiZzT2zYH6bcD9Y6p4JvcCOgup5oVqUNJPgPhlSVyk4qTwp5O73JWpyC1vp/1YX7D9l7xlNepbULLL+fOZIRI0TxY/KdKsxF5GCD21pnrhIT182L6BI0A8kvrISN9suprCvA8qa3bYLGcRE8fKtdvtLsp1TbMDHUOLE3Giew+WwYamZDV9N7dPgAPg5ztltekoJICqT+jX1hwTovFi3tu/XcByhwzl+/FI/kHFgNvCo9vrp2INPNsIr70T5M0Qr9rMZYfeAfHohwurJ3U3Qc8fub0kS5YoEldQ7XXO2PdqYICbXVPSEaM6+3+i1OQGfHvxEKNX/Wk72zA7DlrkEZ9YPwEQ+U9M2/O5/mNyiCrIpbnLJJmDPz3hOZjVTyDOOFxk8ui8RnkZ7D2iG6RkhqYKuoescqzoiW5PITQLLGoK11SAxygczZg+SVNSn0nCVlIV0PcgLaU26UaLWbuBwA==
  template:
    metadata:
      creationTimestamp: null
      name: image-updater-ghcr
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
