apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml
  - reload-trigger.yaml
images:
  - name: ghcr.io/fosleen/vjencanja-backend
    digest: sha256:1bbee0f30134747bae63695fac5237658afb48dbb65af262b88d1775619d98a9
