apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml
  - reload-trigger.yaml
images:
  - name: ghcr.io/fosleen/vjencanja-backend
    digest: sha256:ac23c63912a0ccca065761ef660796bd5068f1d401dfdbb035caed6c9779b0da
