apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml
  - reload-trigger.yaml
images:
  - name: ghcr.io/fosleen/vjencanja-backend
    digest: sha256:1e98e09ade5f7e2ab5d6ca2725180b436f435afeea0809c9a2d2f7354a66ddb4
