---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAR11ejr8QkeIEhWErWuUha5arynMz2l4lSRlSsVuvvBfu88aL+npJMs26JxuSgclWsgOBDy8dkIKNzlYW/3PIT0sob9IpEOfDlDafXdBp4rHb6l7GUvZ1+vqbfg5fc/wYQPh7N3Aloy6rFE0bY5wPS1OUvyoKcVJbV+hCRofqX4Se+Rq5qedA4ykhHQMpnhA6lO06dMXgKleccnAM5qRcsIyZhkyle32c5LYsA4gdXHuRA0w61B+D5a5nMKoRXtmNfZFoauYAxDWRWvtUttDK6ByrjeN8mObeSmLpzWr06ZVnj/wTBRjWiIFDXFE29M4S3AQRnVpAoNonuarzEQq2lYj1/jby0TdBx9u3AdUIVXNvraSELrjxLN50WtJ20fTP37Ag9s/U9LrsCfJgU6/6kGNPss6iXV8GxXFNcQ4t6mlt9UqMOz84P3NeJTziAo7aA9hno0fr70g101gH3CzauMrhxXrnPBlMs0jJZVBS9Hdjfo8aUP3qmQEhET02bi/XZEbes0XMAJ++U9D+Blu+4SDOcCSjaUjOPWcnvwd1LIQUvtsIeyEq8zENlXMlZiP+KxoKTxu2VQGbHV8sM2dK4sYvo1hhrYrtsaq0HkOBf8+3eWqjz3WxhsGUx/dvDhjamJk1VZVaL6//e2LIaRUmKT8BZmVzaj7FOe9fatISi5aLygVo4+vnUaGqD+3I1Jg4wL8NV3vd3fBhRtTh38Op+FJarKp6+W6ivJydXVJHlLluCRul1bt3nrYJG1X5E+Lg6Zm2qIJO7vydUdBJPkYtONduPv3CJHQerouSQBYoWxNMTLuyqpP+ANGr4q/ObcTEnTjIwKYse4Nv4lJQs5iVYEUpw4Bp6JNt7iKib/D4VgEKvb9BMGmeQPHVH7ngjDDJXcg+C1pKExnlK30yK33+bSiMgECm81+Agbeztrh3NcWAxqIB2f6kExd02yb1oCvQM2cZpa9D/gU/Ky7hq2C0jwkQQSrGc
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
