---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCaGHhggGqrYz3oHeboMD8aTgunq6O9SIRvBAptovC3xXVPRzN7cHNx1XBWXbtN+rQqipWeC8xs09KD5+NwPoL1Bp6vovGMCTi4vdRtD1YEbmo9kRrAg+TAR8T5rox5o5TT8ytTPUttbxYWpVMdYBuBVvlgJRXCZT1JOBNP7qCGPS7N9SSvipTmIR6YUoDByl/e7ZtvjUSUjXpv9x3ipLtikY+8OmVrJBAVx0ulFac2Iv9hfY/mO9nU5FVsds1nbDyReoP6hUWIkhWc4z+fCkzAXklAY+r81pDQ88DqZVZ9s/yGfRNZmbcHHLA5DR591nDUp2l2FXqZAJn90NGXfu7s09UdTG+GgnDtY8vTTjbW0VEh2TrHH1caTrJmXUtFS0EN3K/5gCOEuPZ91iprU+xvj1C0jKPeMcuf6mcROx8GH4jkcQTPqKaJHaiGcvub3d+fTMVFTYgUrm82PR2kZx72B8Sbj/aKay7DAXiTF9j9hUbqa0SI1aYc4m52jv7toWkWEB3M7dLKwdtMGyPyVWwg9ZwEr7fklSKzRT5cfPa4GZviwKhjv0udbJ/s5TT/GkVKEJLgsPaoYT9r7JE1rtnr9jASkva3kNZTW5xn+1nn4wXd8SBLWOJLUJXnvf54od91oKlvfsTTXxvOvtFeE0UIIcO5I1ZHLkbmzTIs7LTLkNGg9w3n7YBKPeipC/QYfjoWLTNOQrnKUvjYo3idhWjCdREmYDAZGGaTJpuKPTRWbuCY0WB36aV9KMxM9AlXo7NlwRjuXMhyD+jGiqMgFodDOOCrPyuqMW8TgVix/s6YXemi5yj0l2O4/c3MyjTGnEKkbdLPlWueJDnheydRA0p0q8rjkKpRQ3C5zVe4ZQAbRnyB5dDHSkupSnjUGH9MGQbLgKNQeacqzcjSQjSBDk+b54H6MWQNI+drNoI7
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
