---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCeVEt+KsBaMcMZwb5VGa8tT91ZxI3EGbvIrcPNPIN0nOGFuaYpMVQsM14Mdy1zJRMxlxfx5qiRHA0Jp2rxMdOO41Ggm1csyT2s4BuEAwHzpHhurGDybHk5/ciu8RYArGf+DYy42GVaLLJAvX/ablZgXV3eG74A4l9JLvf6Ce39du+XCcbVB/AkSN5PF6m/e79N5vGeV1/Uhwlp/9OOKjpHKdZTcMGS+EabAm+uKe45mwwCW65xxaD5ZIwXotj2lvc4DLI9CXwdZOwrY/pwAhoUpzN95LT2IMiBULE2Blh/P7/rIF9Rzo9dl3sECEPY7Cjop1bY4t2ZxCPWJUYzX9mWfNi52aTiKNyvq5MO6eaih7Cq6IDhaH35F9rGPmVt2O9vAD1nlrwInAyigYr24lcHmfc0tnr2s0YdXCWUhtRS/aTzyh8qZDvQgOQqBNuhYBjvwM9GaGho79ncMJAiSFpGXHnvswPa42gE49YInLzGgodF81NCCzd9mYRmpBxSH9/jy4Q50+/6dIBsYf7jVacxuA/jjogH3ckfuyEpUjUpEDvm/XufQGhu0QUseef8ySv59oqB0IvWC2uP5Kh4pDjVb953bahAL8n3WJjK/YgpN7cAaYRYZJtuwH0ZTN1+eHcEuxsAVswZHXgLly3y6uxCgnxkkr2RaEa7i9QNijD/PYhZgL3LJKNEXNKj03YhFj6x+vk+2IyOPALwZNabXDNH2gNZmlK+CfxrXfX4CV8mb/n73FZd2dDHVEt/nuFfBWcSEaQnUQjJLoBxDPF6uqzUKB+ToLz5A1IUR6oc/K/3MiDZn+h5aeeUYVuCpDEVkji4pCZEPr4rCN7Jof6tMnFJF9JP9q0MQuKBmHKYLzOiYulTL59CFtrTF0XvPaSwvs0b6xJ16f4GfUptxEeg3Xa/aaTPGnDuiJ9PcQ==
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
